[package]
name = "gps-share"
version = "0.3.1"
authors = [
    "Zeeshan Ali <zeenix@gmail.com>",
    "Dorota Czaplejewicz <dorota.czaplejewicz@puri.sm>",
    "Angus Ainslie <angus@akkea.ca>",
]
categories = ["hardware-support", "command-line-utilities", "command-line-interface", "os::unix-apis"]
keywords = ["serial", "hardware", "system", "RS232", "GPS"]
license = "GPL-2.0+"
readme = "README.md"
repository = "https://github.com/zeenix/gps-share"
description = "Utility to share your GPS device on local network"
edition = "2021"

[dependencies]
serial = "0.3"
clap = { version = "4.5.7", features = ["derive"] }
libc = "0.2.155"
signal-hook = "0.3.17"